version: '3.3'

services:

  mysql:
    image: mysql:8
    restart: always
    container_name: 'erp-system-db'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - host

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'erp-system-messaging'
    ports:
        - 5672:5672
        - 15672:15672
    networks:
      - host

# networks:
#   erp-system-dev:
#     driver: host

networks:
  host:

